// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDphOyKS4UI23Vi8OnFgoae35-WoE0olpw',
    appId: '1:305347177492:web:769f08263eac2f438d0b01',
    messagingSenderId: '305347177492',
    projectId: 'pharmacy-system-632ad',
    authDomain: 'pharmacy-system-632ad.firebaseapp.com',
    storageBucket: 'pharmacy-system-632ad.firebasestorage.app',
    measurementId: 'G-HK00J3PSNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHHnFcBySyG4q5QwzEgku8GW5RR0xbfVQ',
    appId: '1:305347177492:android:41d1f7f5b127f2f38d0b01',
    messagingSenderId: '305347177492',
    projectId: 'pharmacy-system-632ad',
    storageBucket: 'pharmacy-system-632ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD5n90RJfpTMMN24d5PYxp784r_5R4CbA',
    appId: '1:305347177492:ios:89997b3adbb9b6238d0b01',
    messagingSenderId: '305347177492',
    projectId: 'pharmacy-system-632ad',
    storageBucket: 'pharmacy-system-632ad.firebasestorage.app',
    iosBundleId: 'com.example.pharmacySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD5n90RJfpTMMN24d5PYxp784r_5R4CbA',
    appId: '1:305347177492:ios:89997b3adbb9b6238d0b01',
    messagingSenderId: '305347177492',
    projectId: 'pharmacy-system-632ad',
    storageBucket: 'pharmacy-system-632ad.firebasestorage.app',
    iosBundleId: 'com.example.pharmacySystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDphOyKS4UI23Vi8OnFgoae35-WoE0olpw',
    appId: '1:305347177492:web:5289457fd10772738d0b01',
    messagingSenderId: '305347177492',
    projectId: 'pharmacy-system-632ad',
    authDomain: 'pharmacy-system-632ad.firebaseapp.com',
    storageBucket: 'pharmacy-system-632ad.firebasestorage.app',
    measurementId: 'G-BK7NRY0HFX',
  );
}
